// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO users (email, name, password_hash, is_email_verified)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, password_hash, is_email_verified, last_login_at, created_at, updated_at
`

type CreateAuthUserParams struct {
	Email           string `json:"email"`
	Name            string `json:"name"`
	PasswordHash    string `json:"password_hash"`
	IsEmailVerified bool   `json:"is_email_verified"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsEmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, email, name, password_hash, is_email_verified, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByLogin = `-- name: GetAuthUserByLogin :one
SELECT id, email, name, password_hash, is_email_verified, last_login_at, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetAuthUserByLogin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByLogin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthUserEmailVerification = `-- name: UpdateAuthUserEmailVerification :one
UPDATE users SET is_email_verified = $2, updated_at = NOW() WHERE id = $1 RETURNING id, email, name, password_hash, is_email_verified, last_login_at, created_at, updated_at
`

type UpdateAuthUserEmailVerificationParams struct {
	ID              pgtype.UUID `json:"id"`
	IsEmailVerified bool        `json:"is_email_verified"`
}

func (q *Queries) UpdateAuthUserEmailVerification(ctx context.Context, arg UpdateAuthUserEmailVerificationParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAuthUserEmailVerification, arg.ID, arg.IsEmailVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthUserPasswordHash = `-- name: UpdateAuthUserPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAuthUserPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateAuthUserPasswordHash(ctx context.Context, arg UpdateAuthUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
