// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SystemSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	PasswordHash    string             `json:"password_hash"`
	IsEmailVerified bool               `json:"is_email_verified"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
